### ISSUE TITLE
Use a fix version of gdal-async for geotiff-validator

### ISSUE THREAD

**Issue by hblitza** [klips-project/rabbitmq-worker#56]
We should use a fixed version here:
https://github.com/klips-project/rabbitmq-worker/blob/79df44bf5d02be8ba398fc24584e0de1e57c32a9/src/geotiff-validator/package.json#L13

Tests to use `3.2.2`, `3.3.x` or `3.4.x` have failed.
TODO: Dig into the issue / contact the maintainer of `gdal-async`.

**Comment by JakobMiksch** [comment]
fixed with #102
