### ISSUE TITLE
Mattermost Notification: Missing URL handling

### ISSUE THREAD

**Issue by JakobMiksch** [klips-project/rabbitmq-worker#82]
Currently the worker fails if the provided URL is not working. This should be checked and handled. See here: https://github.com/klips-project/rabbitmq-worker/blob/main/src/send-mattermost-message/index.js#L31

This failure causes major troubles to RabbitMQ, because it already happens in the error-handling worker and therefore starts and infinite loop of newly sent messages.

**Comment by weskamm** [comment]
fixed by #95
